### ISSUE TITLE
Color Mismatch

### ISSUE THREAD

**Issue by bilalsal** [mawo87/scats#4]
The color mapping does not seem to be accurate.

For example, the selected cell and its parents cells have 18 elements, but are colored with the color for >=16.
It should be the color of >= 18.
Maybe somewhere in code you are using "greater than" instead of "greater than or equal"?

![color_mismatch](https://cloud.githubusercontent.com/assets/3834295/7479892/f3b88698-f364-11e4-99ad-529922509fd8.png)

**Comment by mawo87** [comment]
The problem was the following:
I have a color range of the these 9 values: ["#fff5eb", "#fee6ce", "#fdd0a2", "#fdae6b", "#fd8d3c", "#f16913", "#d94801", "#a63603", "#7f2704"]

Now when I map the input domain (from min=1 and max=43) to the 9 values I get the following intervals computed by d3:
[1, 3.444444444444444]
[3.444444444444444, 5.888888888888888]
[5.888888888888888, 8.333333333333332]
[8.333333333333332, 10.777777777777777]
[10.777777777777777, 13.222222222222223]
[13.222222222222223, 15.666666666666666]
[15.666666666666666, 18.333333333333332]
[18.333333333333332, 25.222222222222214]
[25.222222222222214, 43]

Obviously the intervals are overlapping (e.g., end of interval 1 and begin of interval 2).
I now round up when computing the legend which seems to solve the issue

**Comment by mawo87** [comment]
This should be solved in commit https://github.com/mawo87/scats/commit/5196e6ac53646e8f84707da4a13ec7cb8032e4c6
